add support for net.IP, net.IPNet, net.HardwareAddr(MAC) and time.Time
itzg/go-flagsfiller pull request #20
Opened 2023-05-04 21:10 UTC by hujun-open

as title, tests included

2023-05-05 13:25 UTC, itzg requested changes
This a great contribution. Thank you for the clean code layout. This will be a great pattern to follow going forward. I added a comment that the Go version can be bumped to get the unit test happy.

2023-05-05 13:25 UTC, itzg commented on addtional_test.go
> +	expeted, _ := time.Parse(time.DateTime, "2001-03-02 13:04:21")
You can bump the Go version for the build

https://github.com/itzg/go-flagsfiller/blob/b3fbd381cf9e74fc96024784b43b3cac2336771d/.github/workflows/test.yml#L19

and module needs to be sync'ed up anyway

https://github.com/itzg/go-flagsfiller/blob/b3fbd381cf9e74fc96024784b43b3cac2336771d/go.mod#L3

2023-05-05 13:25 UTC, itzg commented on flagset.go
> +var supportedStructList = make(map[string]struct{})
Can you add a comment here about the need to give awareness of structs that don't need to be walked into?

2023-05-05 22:47 UTC, hujun-open commented
ok, your comments are address in this commit, including field tag support for the time layout

2023-05-06 19:52 UTC, itzg commented
Thanks for the follow up changes. I forgot ask before, please also add an entry to `docs.go` for these.

I'm not sure yet why the test compilation is failing. It's acting like it is pulling Go 1.2 instead of 1.20, but can't spot the problem yet.

2023-05-06 19:58 UTC, itzg approved these changes
Bumping the setup-go action fixed the test build.

Let me know if you're uncomfortable making the docs change and I'll be glad to follow up with that. Otherwise, these changes are good to go.

2023-05-06 20:24 UTC, hujun-open commented
I have made the doc changes, also a small change on the parsing error msg of timeValue

2023-05-06 20:41 UTC, itzg commented on docs.go
> +# Quick Start
Are you sure markdown syntax works here?

The doc rendering already is aware of section headers:

![image](https://user-images.githubusercontent.com/988985/236645817-062a18db-1dde-4947-a14a-794fa0ce3649.png)

2023-05-06 20:44 UTC, itzg commented on docs.go
> +# Quick Start
My apologies, I didn't know they have since added markdown support:

https://tip.golang.org/doc/comment#syntax

2023-05-06 20:45 UTC, itzg approved these changes
Very nice. Thanks for all of this!

2023-05-06 20:46 UTC, merged

2023-05-06 20:47 UTC, itzg commented
Released in https://github.com/itzg/go-flagsfiller/releases/tag/v1.10.0